import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

import { AgentProvider } from "@/contexts/agent-context";
import { AuthProvider } from "@/contexts/auth-context";
import { FloatingAgent } from "@/agent/components/floating-agent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased scroll-smooth`}
      style={{ scrollbarGutter: "stable" }}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <TRPCReactProvider>
            <AuthProvider>
              <AgentProvider>
                {children}
                <FloatingAgent />
              </AgentProvider>
            </AuthProvider>
          </TRPCReactProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
