import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";
import Image from "next/image";
import { TooltipProvider } from "@/components/ui/tooltip";

import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { SukaKrsAgent } from "@/components/agents/suka-krs-agent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased scroll-smooth`}
      style={{ scrollbarGutter: "stable" }}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <TRPCReactProvider>
            {children}
            <SukaKrsAgent />
          </TRPCReactProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
